<ips:template parameters="$report = null" />
<div style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px; vertical-align: top; font-weight: bold; margin-bottom: 2px;">Claim Details:</div>
<table width="100%" cellpadding="15" cellspacing="0" border="0" style="background: #f9f9f9;">
    <tbody>
        <tr>
            <td dir="ltr">
                <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background: #f9f9f9;" class="responsive_table">
                    <tbody>
                        <tr class="responsive_row">
                            <td dir="ltr" width="250" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px; vertical-align: top;"><strong>Claim Submitted At:</strong></td>
                            <td dir="ltr" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px;">{datetime="$report->created_at" norelative="true"}</td>
                        </tr>
                        <tr class="responsive_row">
                            <td dir="ltr" width="250" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px; vertical-align: top;"><strong>Claim Updated At:</strong></td>
                            <td dir="ltr" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px;">{datetime="$report->updated_at" norelative="true"}</td>
                        </tr>
                        <tr class="responsive_row">
                            <td dir="ltr" width="250" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px; vertical-align: top;"><strong>Your Full Name:</strong></td>
                            <td dir="ltr" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px;">{$report->name}</td>
                        </tr>
                        <tr class="responsive_row">
                            <td dir="ltr" width="250" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px; vertical-align: top;"><strong>Copyright Holder's Full Name:</strong></td>
                            <td dir="ltr" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px;">{$report->copyright_name}</td>
                        </tr>
                        <tr class="responsive_row">
                            <td dir="ltr" width="250" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px; vertical-align: top;"><strong>Your Email Address:</strong></td>
                            <td dir="ltr" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px;">{$report->email}</td>
                        </tr>
                        <tr class="responsive_row">
                            <td dir="ltr" width="250" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px; vertical-align: top;"><strong>Title:</strong></td>
                            <td dir="ltr" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px;">{$report->title}</td>
                        </tr>
                        <tr class="responsive_row">
                            <td dir="ltr" width="250" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px; vertical-align: top;"><strong>Company Name:</strong></td>
                            <td dir="ltr" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px;">{$report->company}</td>
                        </tr>
                        <tr class="responsive_row">
                            <td dir="ltr" width="250" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px; vertical-align: top;"><strong>Telephone:</strong></td>
                            <td dir="ltr" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px;">{$report->phone}</td>
                        </tr>
                        <tr class="responsive_row">
                            <td dir="ltr" width="250" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px; vertical-align: top;"><strong>Address:</strong></td>
                            <td dir="ltr" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px;">{address="$report->address"}</td>
                        </tr>
                        <tr class="responsive_row">
                            <td dir="ltr" width="250" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px; vertical-align: top;"><strong>Describe The Original Work:</strong></td>
                            <td dir="ltr" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px;">{$report->description|raw}</td>
                        </tr>
                        <tr class="responsive_row">
                            <td dir="ltr" width="250" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px; vertical-align: top;"><strong>Digital Signature:</strong></td>
                            <td dir="ltr" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px;">{$report->signature}</td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>
<br>
<div style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px; vertical-align: top; font-weight: bold; margin-bottom: 2px;">Reported Content:</div>
<table width="100%" cellpadding="15" cellspacing="0" border="0" style="background: #f9f9f9;">
    <tbody>
    <tr>
        <td dir="ltr">
            <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background: #f9f9f9;" class="responsive_table">
                <tbody>
                    {{$links = explode(',', $report->urls);}}
                        {{foreach $links as $url}}
                        <tr class="responsive_row">
                            <td dir="ltr" style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 14px;"><a href="{$url}">{$url}<a></td>
                        </tr>
                    {{endforeach}}
                </tbody>
            </table>
        </td>
    </tr>
    </tbody>
</table>