<?php

$lang = array(
    '__app_dmca' => 'DMCA Copyright Claim Manager',

    'menutab__dmca' => 'DMCA Manager',
    'menutab__dmca_icon' => 'flag',

    'menu__dmca_system' => 'System',
    'menu__dmca_system_history' => 'History',
    'menu__dmca_system_reports' => 'Reports',
    'menu__dmca_system_settings' => 'Settings',

    'memberACPProfileTitle_dmca_CopyrightInfringements' => 'Copyright Infringements',

    'frontnavigation_dmca' => 'File A Copyright Claim',

    'notifications__dmca_Claim' => 'Copyright Claims',
    'notifications__dmca_Claim_desc' => 'Receive notifications regarding updates about your filed copyright claims.',

    'mailsub__dmca_notification_submitted' => 'Your copyright claim was submitted',
    'mailsub__dmca_notification_approved' => 'Your copyright claim was approved',
    'mailsub__dmca_notification_onhold' => 'Your copyright claim was placed on hold',
    'mailsub__dmca_notification_denied' => 'Your copyright claim was denied',
    'mailsub__dmca_notification_deleted' => 'The item in your copyright claim has been deleted',
    'mailsub__dmca_notification_firststrike' => 'A copyright claim has been filed against some content you posted. This is your first strike.',
    'mailsub__dmca_notification_secondstrike' => 'A copyright claim has been filed against some content you posted. This is your second strike.',
    'mailsub__dmca_notification_thirdstrike' => 'A copyright claim has been filed against some content you posted. This is your third and last strike.',

    'mailsub__dmca_submitted' => 'Your copyright claim was submitted',
    'mailsub__dmca_approved' => 'Your copyright claim was approved',
    'mailsub__dmca_onhold' => 'Your copyright claim was placed on hold',
    'mailsub__dmca_denied' => 'Your copyright claim was denied',
    'mailsub__dmca_deleted' => 'The item in your copyright claim has been deleted',

    'r__reports' => 'Reports',
    'r__reports_manage' => 'Can manage reports?',

    'dmca_wizard_faq' => 'Start',
    'dmca_wizard_faq_read' => 'I have read the Frequently Asked Questions.',
    'dmca_wizard_faq_error' => 'Please read the Frequently Asked Questions and select the checkbox before proceeding.',
    'dmca_wizard_report' => 'File A Report',
    'dmca_wizard_report_error' => 'Please check the I Understand And Agree checkbox before proceeding.',
    'dmca_wizard_report_submit' => 'File Claim',
    'dmca_wizard_final' => 'Final Steps',

    'dmca_settings' => 'Settings',
    'dmca_settings_tab_claims' => 'Claims Management',
    'dmca_settings_tab_notifications' => 'Claimant Notifications',
    'dmca_settings_tab_form' => 'Claim Form',
    'dmca_settings_groups' => 'Groups',
    'dmca_automatic_deletion' => 'Automatic Claim Deletion',
    'dmca_automatic_deletion_desc' => 'Automatically delete claimed copyright infringement items after a certain period when the claim status is set to Submitted.',
    'dmca_warning_points' => 'Warning Points',
    'dmca_warning_points_desc' => 'Apply an amount of warning points each time a member receives a copyright infringement strike.',
    'dmca_settings_warnings' => 'Warnings',
    'dcma_warning_enable' => 'Enable Warnings',
    'dcma_warning_enable_desc' => 'Give a member a warning with each copyright claim infringement.',
    'dcma_warning_acknowledgement' => 'Require Warning Acknowledgement',
    'dcma_warning_acknowledgement_desc' => 'Require the member acknowledge the warning before they can post again.',
    'dcma_warning_posting_restriction' => 'Posting Restriction',
    'dcma_warning_posting_restriction_desc' => 'Restrict the member from posting for a specified time when receiving a copyright infringement strike.',
    'dcma_warning_posting_restriction_none' => 'Do Not Restrict Posting',
    'dcma_warning_moderate_content' => 'Moderate Content',
    'dcma_warning_moderate_content_desc' => 'Moderate the member\'s content for a specified time when receiving a copyright infringement strike.',
    'dcma_warning_moderate_content_none' => 'Do Not Moderate Content',
    'dmca_warning' => 'Warning Reason',
    'dmca_warning_desc' => 'The warning reason that is applied when a member receives a copyright infringement strike.',
    'dmca_group' => 'Infringing Group',
    'dmca_group_desc' => 'The group the member will be moved to when they receive their third strike. Select none to not move a member.',
    'dmca_claim_intro' => 'Claim Form Intro',
    'dmca_claim_intro_desc' => 'Text that will be shown above the claim submission form.',
    'dmca_faq' => 'Frequently Asked Questions',
    'dmca_faq_desc' => 'Text that will be shown on the first page when filing a new claim.',
    'dmca_final' => 'Final Steps',
    'dmca_final_desc' => 'Enter some text that will shown to the member after they file a claim.',
    'dmca_approval_email' => 'Default Claim Approved Email',
    'dmca_approval_email_desc' => 'This may be edited on an individual claim basis.',
    'dmca_onhold_email' => 'Default Claim On Hold Email',
    'dmca_onhold_email_desc' => 'This may be edited on an individual claim basis.',
    'dmca_denied_email' => 'Default Claim Denied Email',
    'dmca_denied_email_desc' => 'This may be edited on an individual claim basis.',
    'dmca_deleted_email' => 'Default Deleted Item Email',
    'dmca_deleted_email_desc' => 'The email that will be sent went the copyright claimed item has been deleted.',
    'dmca_submitted_email' => 'Default Claim Submitted Email',
    'dmca_submitted_email_desc' => 'The email that will be sent when a copyright claim is submitted.',
    'dmca_settings_tab_strike_notifications' => 'Infringing Member Notifications',
    'dmca_first_strike_email' => 'First Strike Email',
    'dmca_second_strike_email' => 'Second Strike Email',
    'dmca_third_strike_email' => 'Third Strike Email',

    'name' => 'Your Full Name',
    'copyright_name' => 'Copyright Holder\'s Full Name',
    'email' => 'Your Email Address',
    'title' => 'Title',
    'company' => 'Company Name',
    'phone' => 'Telephone',
    'member_id' => 'Infringing Member',
    'member_id_desc' => 'The member responsible for posting the copyrighted material.',
    'type' => 'Content Type',
    'type_desc' => 'Select the type of content that contains the copyrighted material.',
    'item' => 'Content Item',
    'item_desc' => 'Select the item containing the copyrighted material. You must submit a report for each claimed item.',
    'urls' => 'Infringing URLs',
    'urls_desc' => 'Post a link of each URL containing the copyrighted material.',
    'description' => 'Describe The Original Work',
    'description_desc' => 'Describe the copyrighted material in full detail, including links to the original work or evidence of source material.',
    'accept_terms' => 'I Understand And Agree',
    'accept_terms_desc' => 'By checking this box, you attest, under penalty of perjury, that you have a good faith belief that use of the material in this report is not authorized by the copyright owner, its agent, or the law; AND you are authorized to act on behalf of the copyright owner; AND you understand, under 17 U.S.C. § 512(f), you may be liable for any damages, including costs and attorneys\' fees, if you knowingly materially misrepresent reported material.',
    'signature' => 'Digital Signature',
    'signature_desc' => 'By entering your name, you affirm all information is true and accurate while agreeing to the policies on this page.',
    'report_id' => 'Report',
    'created_at' => 'Created At',
    'dmca_reports_id' => 'ID',
    'dmca_reports_name' => 'Reporting Person',
    'dmca_reports_email' => 'Reporting Email',
    'dmca_reports_member_id' => 'Infringing Member',
    'dmca_reports_report' => 'Report',
    'dmca_reports_item' => 'Reported Item',
    'dmca_reports_created_at' => 'Reported At',
    'dmca_reports_status' => 'Status',
    'dmca_reports_automation' => 'Automation',

    'dmca_report_submitted' => 'Submitted',
    'dmca_report_approved' => 'Approved',
    'dmca_report_denied' => 'Denied',
    'dmca_report_pending' => 'Pending',
    'dmca_report_on_hold' => 'On Hold',
    'dmca_report_deleted' => 'Deleted',

    'dmca_approve' => 'Approve',
    'dmca_deny' => 'Deny',
    'dmca_on_hold' => 'Place On Hold',
    'dmca_delete' => 'Delete',

    'dcma_send_mail' => 'Send Email',

    'dcma_chart_infringements' => 'Infringements',
    'dcma_chart_infringements_title' => 'Copyright Infringements For Member',
);
